// Served at /manifest.webmanifest and linked from <head> by Next. Colors match
// primary.main and the light background.default in utils/theme.js. Icons are
// generated by `npm run icons:generate` (scripts/generateIcons.mjs).
export default function manifest() {
  return {
    id: '/',
    name: 'SLICs',
    short_name: 'SLICs',
    description: 'Look up SLIC addresses, phone numbers, and driver comments.',
    // The installed app opens on the lookup page, not the sign-in landing.
    // Signed-out users are bounced to '/' by the page itself.
    start_url: '/home',
    scope: '/',
    display: 'standalone',
    background_color: '#edf3fc',
    theme_color: '#039be5',
    icons: [
      {
        src: '/android-chrome-192x192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/android-chrome-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      // Opaque, inset variants for launchers that apply a circular/squircle
      // mask; the transparent edge-to-edge mark above would be clipped.
      {
        src: '/maskable-icon-192x192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'maskable',
      },
      {
        src: '/maskable-icon-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  };
}
