const jobs = [
  {
    name: 'LV30',
    start: '11:30',
    route: [
      {
        name: 'Casper',
        slic: '18CAS',
        equipment: 'Long box',
        description: 'Drop and hook',
        pullTime: '13:00',
        meal: 'no',
        comments: [],
      },
      {
        name: 'Betpa',
        slic: '1809',
        equipment: 'Long box',
        description: 'Back to Betpa',
        pullTime: 'n/a',
        meal: 'no',
        comments: [],
      },
      {
        name: 'Bird box',
        slic: '18DK',
        equipment: 'Long box',
        description: 'Drop and hook',
        pullTime: '16:30',
        meal: 'yes',
        comments: [],
      },
      {
        name: 'Allpa',
        slic: '1819',
        equipment: 'Long box',
        description: 'Bring to Allpa',
        pullTime: 'n/a',
        meal: 'no',
        comments: [],
      },
      {
        name: 'Lulu',
        slic: '18LU',
        equipment: 'Bobtail',
        description: 'Drop and hook',
        pullTime: '18:30',
        meal: 'no',
        comments: [
          {
            com: 'Employee will give you glad handle lock to put on trailer you bring back.',
          },
        ],
      },
      {
        name: 'Betpa',
        slic: '1809',
        equipment: 'Long box',
        description: 'Back to Betpa',
        pullTime: 'n/a',
        meal: 'no',
        comments: [
          {
            com: 'If only a few gaylords then wait to be unloaded and bring trailer back to Lulu.',
          },
        ],
      },
      {
        name: 'Lulu',
        slic: '18LU',
        equipment: 'Long box',
        description: 'Drop and hook',
        pullTime: 'n/a',
        meal: 'no',
        comments: [
          {
            com: 'Put glad handle lock on trailer.',
          },
        ],
      },
      {
        name: 'Betpa',
        slic: '1809',
        equipment: 'Long box',
        description: 'Back to Betpa',
        pullTime: 'n/a',
        meal: 'no',
        comments: [],
      },
      {
        name: 'Uline',
        slic: '1813',
        equipment: 'Set of doubles',
        description: 'Drop',
        pullTime: 'n/a',
        meal: 'no',
        comments: [{ com: 'Bring doubles to Uline.' }],
      },
      {
        name: 'Betpa',
        slic: '1809',
        equipment: 'Bob tail',
        description: 'n/a',
        pullTime: 'n/a',
        meal: 'no',
        comments: [],
      },
    ],
  },
  {
    name: 'LV25',
    start: '11:30',
    route: [
      {
        name: 'Custom Filters Direct',
        slic: '18CFD',
        equipment: 'Long box',
        description: 'Drop and hook',
        pullTime: '14:30',
        meal: 'no',
        comments: [],
      },
      {
        name: 'Betpa',
        slic: '1809',
        equipment: 'Long box',
        description: 'Back to Betpa',
        pullTime: 'n/a',
        meal: 'no',
        comments: [],
      },
      {
        name: 'Meal',
        slic: 'n/a',
        equipment: 'n/a',
        description: 'Meal',
        pullTime: '17:00',
        meal: 'yes',
        comments: [],
      },
      {
        name: 'Smart Warehouse',
        slic: '18SW',
        equipment: 'Long box',
        description: 'Drop and hook',
        pullTime: '18:30',
        meal: 'no',
        comments: [],
      },
      {
        name: 'Betpa',
        slic: '1809',
        equipment: 'Long box',
        description: 'Back to Betpa',
        pullTime: 'n/a',
        meal: 'no',
        comments: [],
      },
      {
        name: 'Work as Assigned',
        slic: '1809',
        equipment: '',
        description: 'Work as assigned',
        pullTime: 'n/a',
        meal: 'no',
        comments: [],
      },
    ],
  },
];

export { jobs };
